### ISSUE TITLE
I think it's better to remove the Eigen's dependency.

### ISSUE THREAD

**Issue by asimay** [ros-perception/laser_geometry#15]

**Comment by vrabaud** [comment]
agreed, it seems to only be used for matrix multiplication. Pull request welcome.

**Comment by asimay** [comment]
I will try to clean later if I know how to use this filters module..
and i cannot see obvious difference from the output data  in rviz...
can you instruct me on how to use? just build package and launch a scan_to_cloud_filter_chain node, and config the filters yaml files, remap the topic, all above is ok?

**Comment by asimay** [comment]
I removed eigen totally, and tidy up the cmake files redundancy.
please check later, i will pull a request.

**Comment by asimay** [comment]
I commited the code, please check. thanks.
