### ISSUE TITLE
this 3 project package cannot build success together if use catkin_make ,default with -j4 option. I think it need to tidy up the cmake files.

### ISSUE THREAD

**Issue by asimay** [ros-perception/laser_geometry#16]
this 3 project package cannot build success together if use catkin_make ,default with -j4 option. I think it need to tidy up the cmake files.

**Comment by vrabaud** [comment]
Please post the compilation issue you are getting.

**Comment by asimay** [comment]
hi dear vra,
1. I cannot use PointCloudFootprintFilter, filter content is:

cloud_filter_chain:
- type: laser_filters/PointCloudFootprintFilter
  name: footprint_filter
  params:
    inscribed_radius: 0.325

roslaunch error.
![pointcloud error](https://cloud.githubusercontent.com/assets/8703449/13345955/06f58c06-dc9e-11e5-81a6-7d56d4822a05.png)

I tried many times and seek for the root, but cannot find out what reason... can you help me?

**Comment by asimay** [comment]
1. build error: default catkin_make, it is make -j4 -l4:
   ![builderror 1](https://cloud.githubusercontent.com/assets/8703449/13346137/20df7a54-dc9f-11e5-9454-ac85245a4206.png)
   ![builderror 2](https://cloud.githubusercontent.com/assets/8703449/13346144/27a91390-dc9f-11e5-8e92-b5a03f0a77e3.png)

**Comment by asimay** [comment]
sorry, the build error is caused by my virtual machine's " virtual memory exhausted."

**Comment by asimay** [comment]
It's ok if solve virtual memory problem..

**Comment by asimay** [comment]
![image](https://cloud.githubusercontent.com/assets/8703449/13348406/497734de-dcae-11e5-8fca-71e6ffd7722a.png)

**Comment by asimay** [comment]
and get no cloud data. but can get laser scan topic data.

**Comment by vrabaud** [comment]
This is not a build issue anymore, just usage. Unless you can reproduce that error, by getting a rosbag in that bug report, we cannot help.

**Comment by asimay** [comment]
dear vra, I  can get cloud point, but still get following error:
what the reason?
![33](https://cloud.githubusercontent.com/assets/8703449/13384595/fd958da6-ded1-11e5-9e78-7587d0e365ca.png)

**Comment by asimay** [comment]
still cannot solve above problem "could not find pointcloudfootprintfilter". is this caused by msg type is not compatible?

**Comment by vrabaud** [comment]
This is a different issue now. Just use rosgraph to introspect and rostopic for the types.
