### ISSUE TITLE
how to use transformLaserScanToPointCloud

### ISSUE THREAD

**Issue by nikitaporje** [ros-perception/laser_geometry#23]
Hi,
I have an hokuyo lidar with me, output file of lidar gives me Sensor_msg/Laserscan topic withchi gives me 2D data. I want to convert it into 3D sensor_msg/PointCloud2 data using your package. To do thet i have to use transformLaserScanToPointCloud function. Can you please help me with this, how can i use it with my data so that i can get final bag file with sensor_msg/PointCloud2 topic.

Thank you

**Comment by vrabaud** [comment]
This is not a bug, please ask your questions on http://answers.ros.org/questions/ or follow the tutorials at http://wiki.ros.org/laser_pipeline/Tutorials/IntroductionToWorkingWithLaserScannerData
