### ISSUE TITLE
Melodic Release

### ISSUE THREAD

**Issue by wjwwood** [ros-perception/laser_geometry#35]
@jonbinney I'm going to go ahead and do the melodic release using the existing version. I hope you don't mind, but we can release a new version at anytime.

**Comment by wjwwood** [comment]
https://github.com/ros/rosdistro/pull/17330

**Comment by wjwwood** [comment]
Actually: https://github.com/ros/rosdistro/pull/17331

**Comment by jonbinney** [comment]
Great!
