### ISSUE TITLE
Noetic dependency on Python 2 numpy

### ISSUE THREAD

**Issue by sloretz** [ros-perception/laser_geometry#48]
It looks like the [noetic source entry for laser_geometry](https://github.com/ros/rosdistro/blob/1b96f7c4f230e878f9901a6cc3465af9cbca22fc/noetic/distribution.yaml#L146-L151) says to use the branch `indigo-devel`, but the `package.xml` on that branch depends on the Python 2 rosdep key `python-numpy`

https://github.com/ros-perception/laser_geometry/blob/83c798893675d7af5347a9d5e6f26df5dd8852e3/package.xml#L29

It should use the [rosdep key `python3-numpy`](https://github.com/ros/rosdistro/blob/1b96f7c4f230e878f9901a6cc3465af9cbca22fc/rosdep/python.yaml#L5134) in `Noetic` instead.

**Comment by jonbinney** [comment]
Damn.... i was really hoping to avoid branching forever :-)

@sloretz do you know if there is a way to make the dependency in the `package.xml` conditional on the rosdistro? If not I'll go ahead and make the branch.

**Comment by jonbinney** [comment]
Oh! There totally is a way....
```
<exec_depend condition="$ROS_DISTRO == melodic">python-numpy</exec_depend>
<exec_depend condition="$ROS_DISTRO == noetic">python3-numpy</exec_depend>
```
@sloretz does that sound like a reasonable approach?

**Comment by sloretz** [comment]
> @sloretz does that sound like a reasonable approach?

I'd recommend using `ROS_PYTHON_VERSION == 2` or `ROS_PYTHON_VERSION == 3` instead. That way it will work for people who are using Python 3 for existing distros, like Arch melodic users. Here's an example: https://github.com/ros/catkin/pull/1025/files this page covers it too: http://wiki.ros.org/UsingPython3/SourceCodeChanges#Changing_dependencies_in_your_package.xml

**Comment by jonbinney** [comment]
Fixed in https://github.com/ros-perception/laser_geometry/pull/49. @sloretz do you need a release into noetic right now? Or is this enough for the moment?

**Comment by sloretz** [comment]
> do you need a release into noetic right now? Or is this enough for the moment?

This is good for now. Thanks!

Releasing will come later when there are packages for Ubuntu Focal. Right now the [existing `laser_geometry` source entry](https://github.com/ros/rosdistro/blob/2acbed536765f23f1a720d18f0c97f543c9dbf6c/noetic/distribution.yaml#L152) is good enough.
