### ISSUE TITLE
Release laser_geometry to Noetic?

### ISSUE THREAD

**Issue by sloretz** [ros-perception/laser_geometry#57]
Would you mind releasing `laser_geometry` to ROS Noetic? It looks like all of its dependencies have been released, and recursively 121 repos need it.

I'm not sure how much work it will need. At a minimum it needs #56.

**Comment by jonbinney** [comment]
Sure thing! I should have time to realease it today or tomorrow.

**Comment by jonbinney** [comment]
Release 1.6.5 created for noetic, PR to rosdistro is here: https://github.com/ros/rosdistro/pull/24083
