### ISSUE TITLE
[ROS 2] projection_test timing out on macOS

### ISSUE THREAD

**Issue by jacobperron** [ros-perception/laser_geometry#62]
For the last couple days, the test has been timing out on macOS nightly CI:

- https://ci.ros2.org/view/nightly/job/nightly_osx_repeated/2019/testReport/junit/(root)/laser_geometry/projection_test_gtest_missing_result/
- https://ci.ros2.org/view/nightly/job/nightly_osx_repeated/2018/testReport/junit/(root)/laser_geometry/projection_test_gtest_missing_result/

Example output:

```
06:31:12 5: [==========] Running 1 test from 1 test case.
06:31:12 5: [----------] Global test environment set-up.
06:31:12 5: [----------] 1 test from laser_geometry
06:31:12 5: [ RUN      ] laser_geometry.projectLaser2
06:34:12     Test #5: projection_test ..................***Timeout 180.13 sec
```

I haven't seen similar failures for other platforms.

**Comment by dirk-thomas** [comment]
Fixed by #63.
