### ISSUE TITLE
Eigen3 not found in Dashing

### ISSUE THREAD

**Issue by asobhy-qnx** [ros-perception/laser_geometry#64]
find_package(eigen3_cmake_module REQUIRED) needs to be added to ros-perception/laser_geometry/CMakeLists.txt for Dashing branch

**Comment by asobhy-qnx** [comment]
@dirk-thomas

**Comment by clalancette** [comment]
@asobhy-qnx Are you willing to submit a PR to do it?  I don't currently have a Dashing environment setup to test.

**Comment by asobhy-qnx** [comment]
yes I can submit a PR

**Comment by clalancette** [comment]
I think this was fixed by #65 (and further by #68), so I'm going to go ahead and close this.  Feel free to reopen if you think this is in error.
